### ISSUE TITLE
Password reset causing password hash to become unreadable

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-authn-password#20]
Hash becomes a non-string value when password reset is performed in production mode.

```
2017-05-30T01:37:40.664Z - critical: worker: uncaught error: TypeError: Cannot read property 'split' of undefined
    at Object.api.verifyPasswordHash (.../node_modules/bedrock-authn-password/lib/auth.js:421:20)
    at .../node_modules/bedrock-authn-password/lib/auth.js:499:11
    at fn (.../node_modules/bedrock-authn-password/node_modules/async/lib/async.js:746:34)
    at .../node_modules/bedrock-authn-password/node_modules/async/lib/async.js:1213:16
    at .../node_modules/bedrock-authn-password/node_modules/async/lib/async.js:166:37
    at .../node_modules/bedrock-authn-password/node_modules/async/lib/async.js:706:43
    at .../node_modules/bedrock-authn-password/node_modules/async/lib/async.js:167:37
    at Immediate.<anonymous> (.../node_modules/bedrock-authn-password/node_modules/async/lib/async.js:1206:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5) workerPid=4687
```

**Comment by msporny** [comment]
This issue is fixed by upgrading to bedrock-authn-password ^4.0.0.
